<?php

return [
    'site_name'=>'Virob',
    'site_url'=>'https://virob.com/',
    'site_domain'=>'Virob.com',
    'site_logo'=>'resources/assets/imgs/logo.png',
    'site_currency_id'=>2,
    'site_language_id'=>1,
    'site_logo_large'=>'resources/assets/imgs/logo.png',
    'fav_icon'=>'resources/assets/imgs/fav-icon.png',
    'site_meta_title'=>'virob.com',
    'site_meta_keyword'=>'virob.com',
    'site_meta_description'=>'virob.com',
    'analytical_code'=>'',
    'address'=>'Example Street 68, Mahattan, New York, USA.',
    'phone'=>'+00 123 456 789',
    'user_login'=>1,
    'user_registration'=>1,
    'captcha_code'=>0,
    'email_confirmation'=>0,
    'noreply_email'=>'support@virob.com',
    'enquiry_receive_type'=>0,
    'outbound_email_api'=>'',
    'transaction_pin'=>1,
    'site_status'=>1,
    'related_applications'=>'',
    'site_offline_message'=>'SITE IS  UNDER MAINTENANCE , WILL COME BACK SOON.',
    'user_authentication_limit'=>10,
    'left_ads_count'=>0,
    'right_ads_count'=>0,
    'top_ads_count'=>0,
    'bottom_ads_count'=>0,
    'ads_type_value'=>'',
    'footer_content'=>'2017-18 © virob.com. All Rights Reserved.',
    'language_iso_code'=>'eng',
	'outbound_email_configure'=>'{\"service\":1,\"driver\":2,\"smtp\":{\"driver\":\"smtp\",\"host\":\"mail.virob.com\",\"port\":465,"encryption\":\"ssl\",\"username\":\"noreply@virob.com\",\"password\":\"ejugiter@123\",\"name\":\"virob\"},\"sendgrid\":{\"driver\":\"smtp\",\"host\":\"smtp.sendgrid.net\",\"port\":587,\"encryption\":\"tls\",\"username\":\"onlinesensor\",\"password\":\"ejugiter@123\"}}',
	'noreplay_emailid'=>'noreply@virob.com',
	'address'=> (object)['country'=>"India"],
];
