<?php

return [
	'CURRENCY_CONVERSION'=>['DEBIT'=>5, 'CREDIT'=>6, 'POST_TYPE'=>null],
	'WITHDRAW'=>['DEBIT'=>7, 'POST_TYPE'=>16],
    'WITHDRAW_CANCEL'=>['CREDIT'=>12, 'POST_TYPE'=>16],
	'ORDER_PAYMENT_COMMISSION'=>['DEBIT'=>44, 'POST_TYPE'=>14],
    'ORDER_PAYMENT_TO_MERCHANT'=>['CREDIT'=>45, 'POST_TYPE'=>14],
	'REDEEM_RETURN'=>['CREDIT'=>4, 'POST_TYPE'=>13],
	'REDEEM'=>['DEBIT'=>3, 'POST_TYPE'=>13],
	'CASHBACK'=>['CREDIT'=>2, 'POST_TYPE'=>13],
    'CASHBACK_RETURN'=>['DEBIT'=>1, 'POST_TYPE'=>13],
	'ORDER_PAYMENT'=>['DEBIT'=>27, 'POST_TYPE'=>13],	
	'ORDERS'=>[1=>[1=>53, 2=>52, 3=>51], 2=>[0=>36]],
	'ADD_FUND'=>['CREDIT'=>38, 'POST_TYPE'=>12],
	'REFUND'=>['CREDIT'=>39, 'POST_TYPE'=>null],
	'ORDER_REFUND'=>['DEBIT'=>21, 'POST_TYPE'=>null],
	'MR_ORDERS'=>['GET_CASHBACK'=>51, 'REDEEM'=>52, 'PAY'=>53],    
    
    'FUND_TRANS'=>['DEBIT'=>19, 'CREDIT'=>20, 'POST_TYPE'=>11],         
    'REFERRAL_BONUS'=>['CREDIT'=>16, 'POST_TYPE'=>15],    
    'SIGN_UP_BONUS'=>['CREDIT'=>14, 'POST_TYPE'=>15],
    'TAX_DEDUCTION'=>['DEBIT'=>42, 'POST_TYPE'=>null],
    'TAX_RETURN'=>[ 'CREDIT'=>43, 'POST_TYPE'=>null],        
    'CASHBACK_REFERRAL_BONUS'=>['CREDIT'=>46, 'POST_TYPE'=>null],
    'CASHBACK_REFERRAL_BONUS_RETURN'=>['DEBIT'=>49, 'POST_TYPE'=>null],	
    'REFERRAL_SIGNUP_BONUS'=>['CREDIT'=>16, 'POST_TYPE'=>null],
    'ORDER_PAYMENT_RETURN'=>['CREDIT'=>28, 'POST_TYPE'=>13],          
    
];
